# Muhammad Zain Ikhlaq
First ML Lab. <br>
Lab Engineer: Ma'am Iram Tariq Bhatti


In [ ]:
# Trying out print
print("Hello, Machine Learning World!")

Hello, Machine Learning World!


In [ ]:
# Mounting drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Reading sample data from environment
import pandas as pd

data = pd.read_csv('/content/sample_data/mnist_test.csv')

In [ ]:
# Saving changes to environment
data.to_csv('/content/sample_data/output_data.csv')

In [ ]:
# BMI - testing numpy

import numpy as np
heights = np.array([1.75, 1.80, 1.65]) # in meters
weights = np.array([65, 78, 50]) # in kg

bmi = weights / (heights ** 2)
print(bmi)

[21.2244898  24.07407407 18.36547291]


In [ ]:
# Data Preprocessing
data = np.array([4.0, 5.0, 6.0, 8.0, 10.0])
normalized_data = (data - np.mean(data)) / np.std(data)
print(normalized_data)

[-1.2070197  -0.74278135 -0.27854301  0.64993368  1.57841037]


In [ ]:
# Dot Product
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [ ]:
# Linear Regression
X = np.array([[1, 2], [3, 4], [5, 6]])
beta = np.array([0.5, 1.5])
b = 0.1
y_pred = np.dot(X, beta) + b
print(y_pred)

[ 3.6  7.6 11.6]


#Arrays vs List

In [ ]:

list_a = [1, 2, 3]
list_b = [4, 5, 6]
result = [a + b for a, b in zip(list_a, list_b)]
print(result) # Output: [5, 7, 9]

[5, 7, 9]


In [ ]:
# Using numpy
import numpy as np
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result = array_a + array_b
print(result) # Output: [5, 7, 9]

[5 7 9]


In [ ]:
# Array Addition and Multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b) # Output: [5, 7, 9]
print(a * b) # Output: [4, 10, 18]

[5 7 9]
[ 4 10 18]


In [ ]:
# Broadcasting
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
print(a + b) # Output: [[2, 4, 6], [5, 7, 9]]

[[2 4 6]
 [5 7 9]]


In [ ]:
# Reshaping Arrays
a = np.array([1, 2, 3, 4, 5, 6])
a_reshaped = a.reshape(2, 3) # 2 rows, 3 columns
print(a_reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Flattening
a_flat = a_reshaped.flatten()
print(a_flat) # Output: [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [ ]:
# Creating a 1D Array from a List
import numpy as np
array_1d = np.array([10, 20, 30, 40])
print(array_1d)

[10 20 30 40]


In [ ]:
# Creating a 2D Array (Matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Performing Operations
array_sum = array_1d + 5 # Add 5 to every element
print(array_sum)

[15 25 35 45]


In [ ]:
# Generating a Random Matrix
random_matrix = np.random.random((3, 3))
print(random_matrix)

[[0.59570557 0.55392291 0.59462749]
 [0.67935931 0.20839889 0.27098491]
 [0.19113698 0.19087864 0.41716637]]


In [ ]:
# Matrix Operations
random_matrix_scaled = random_matrix * 100 # Scale all values by 100
print(random_matrix_scaled)

[[59.57055745 55.39229054 59.4627488 ]
 [67.93593083 20.83988916 27.09849072]
 [19.1136977  19.08786444 41.71663736]]


In [ ]:
# Reshaping Arrays
reshaped_array = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3) # 2 rows, 3 columns
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Slicing Arrays
# Slice first two rows and first two columns
sliced_array = reshaped_array[:2, :2]
print(sliced_array)

[[1 2]
 [4 5]]


# Mini Challenge
- Takes in an array of any size. <br>
- Normalizes the array (i.e., scales the elements to be between 0 and 1).<br>
- Testing on random array.

In [ ]:
import numpy as np

def normalize_array(arr):
  """Normalizes a NumPy array to values between 0 and 1."""
  min_val = np.min(arr)
  max_val = np.max(arr)
  normalized_arr = (arr - min_val) / (max_val - min_val)
  return normalized_arr

# Testing function with random array
random_array = np.random.rand(5, 5) * 100 # Taking values 0-100
print("Original array:")
print(random_array)

normalized_random_array = normalize_array(random_array)
print("\nNormalized array:")
print(normalized_random_array)

Original array:
[[20.3744391  30.57401474 99.43082498 57.29277271 18.21393673]
 [93.49723889 48.24384929 78.55343093 57.28383856 36.42677035]
 [45.12164567 93.59242741 15.19001895 68.11335725 32.92073379]
 [76.53547723 70.50517219  0.78982596 63.73452076 74.36091894]
 [69.80593004 67.37644807 43.958213   66.96835775 51.51523252]]

Normalized array:
[[0.19854435 0.30194533 1.         0.57281402 0.17664167]
 [0.93984665 0.48107809 0.78834973 0.57272344 0.36127923]
 [0.4494259  0.94081165 0.14598588 0.68251064 0.32573583]
 [0.76789217 0.70675831 0.         0.63811899 0.745847  ]
 [0.69966956 0.67504002 0.43763128 0.67090289 0.51424263]]
